name: Update latest git command
description: Update git command to the latest version
branding:
  icon: git-branch
  color: gray-dark
author: kzrnm
runs:
  using: composite
  steps:
    - name: MacOS - Install latest git
      if: runner.os == 'macOS'
      run: brew update && brew upgrade git
      shell: bash

    - name: Windows - Install latest git
      if: runner.os == 'Windows'
      run: winget install --id Git.Git -e --source winget --silent --disable-interactivity --accept-source-agreements --accept-package-agreements || true
      shell: bash

    - name: Linux - Install latest git
      uses: ./.github/actions/build-git
      if: runner.os == 'Linux'

    - name: Check git version
      run: git --version | tee $GITHUB_STEP_SUMMARY
      shell: bash
