name: Test & Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force-publish:
        description: Force publish even if tests fail
        required: false
        type: boolean
        default: false
env:
  Module: git-completion
jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      is-prerelease: ${{ steps.get-version.outputs.is-prerelease }}
      new-tag: ${{ steps.is-new-version.outputs.new-tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Update git command
        uses: ./.github/actions/latest-git
      - name: Get Module Version
        id: get-version
        shell: pwsh
        run: |
          Import-Module "./src/${env:Module}.psd1"
          $m = (Get-Module $env:Module)
          $version = $m.Version.ToString()
          $prerelease = $m.PrivateData.PSData.Prerelease
          if ($prerelease) {
            Write-Output "is-prerelease=true" | Tee-Object "$env:GITHUB_OUTPUT" -Append
            $prerelease = "-$prerelease"
          } else {
            Write-Output "is-prerelease=false" | Tee-Object "$env:GITHUB_OUTPUT" -Append
          }
          Write-Output "version=$version$prerelease" | Tee-Object "$env:GITHUB_OUTPUT" -Append

      - name: Check tag
        uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with:
          tag: v${{ steps.get-version.outputs.version }}

      - name: is new version?
        id: is-new-version
        run: |
          TAG=""
          if [ "${{ steps.check-tag.outputs.exists }}" = "false" ]; then
            echo "new version tag project: ${{ steps.get-version.outputs.version }}"
            TAG="v${{ steps.get-version.outputs.version }}"
          fi
          echo "new-tag=$TAG" | tee -a "$GITHUB_OUTPUT"
  test:
    uses: ./.github/workflows/test.yml
    with:
      continue-on-error: ${{ inputs.force-publish }}

  new-version-only:
    runs-on: ubuntu-latest
    needs: [get-version, test]
    if: ${{ needs.get-version.outputs.new-tag != '' && (! failure() || inputs.force-publish) }}
    steps:
      - run: echo "new-version"

  publish:
    runs-on: ubuntu-latest
    environment:
      name: actions
      url: https://github.com
    needs: [get-version, new-version-only]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Push tag
        id: tag-version
        run: |
          tag="${{ needs.get-version.outputs.new-tag }}"
          git tag "$tag"
          git push origin "$tag"

      - name: Create release
        uses: ncipollo/release-action@v1
        id: create-release
        with:
          tag: ${{ needs.get-version.outputs.new-tag }}
          name: Version ${{ needs.get-version.outputs.version }}
          body: ${{ github.server_url }}/${{ github.repository }}/blob/${{ steps.tag-version.outputs.new_tag }}/CHANGELOG.md
          prerelease: ${{ needs.get-version.outputs.is-prerelease }}

      - name: Install-Module PowerShellGet
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module PowerShellGet -MinimumVersion " 3.0.23-beta23" -AllowPrerelease -Repository PSGallery -AllowClobber -Force
          Get-PSResourceRepository PSGallery # https://github.com/PowerShell/PSResourceGet/issues/1806

      - name: Publish
        shell: pwsh
        run: |
          $NUGET_KEY = "${{ secrets.PWSH_NUGET_KEY  }}"
          tools/dist.ps1 -TagName "v${{ needs.get-version.outputs.version }}"
          Import-Module PowerShellGet
          Publish-PSResource -Path "./$env:Module" -APIKey "$NUGET_KEY" -Repository PSGallery
